### ISSUE TITLE
FilePushRequestHandler inserts too many versions

### ISSUE THREAD

**Issue by rmatil** [p2p-sync/sync#25]
When creating a File consisting of only 1 chunk, 3 versions are generated
in the ObjectStore. Make sure, that only one version is inserted

**Comment by rmatil** [comment]
This may be related to p2p-sync/sync#23

**Comment by rmatil** [comment]
I hardly believe this is caused due to the underlying file system or the pathwatcher.
Note, that there are 3 notifications from PathEventListener:

```
[10:57:14,348] [defaultEventExecutorGroup-2-21                    ] [DEBUG] [LocalStateObjectDataReplyHandler.java:184]: Using org.rmatil.sync.core.messaging.fileexchange.offer.FileOfferRequestHandler as handler for request 228160e6-3675-4ba0-a95d-44c95969f0b3 
[10:57:14,361] [questCallback-228160e6-3675-4ba0-a95d-44c95969f0b3] [TRACE] [Node.java:185]: Sending object to peer with address 192.168.1.43:4003 
[10:57:24,642] [defaultEventExecutorGroup-2-25                    ] [DEBUG] [LocalStateObjectDataReplyHandler.java:184]: Using org.rmatil.sync.core.messaging.fileexchange.push.FilePushRequestHandler as handler for request 072cfc60-38bd-4959-9ae3-e10d4dbae166 
[10:57:24,648] [questCallback-072cfc60-38bd-4959-9ae3-e10d4dbae166] [INFO ] [FilePushRequestHandler.java:98]: Writing chunk 0 for file test1.jpg for exchangeId 072cfc60-38bd-4959-9ae3-e10d4dbae166 
[10:57:24,658] [questCallback-072cfc60-38bd-4959-9ae3-e10d4dbae166] [DEBUG] [ObjectStoreFileChangeListener.java:81]: Got notified from event bus: AddOwnerAndAccessTypeToObjectStoreBusEvent for file test1.jpg 
[10:57:24,659] [questCallback-072cfc60-38bd-4959-9ae3-e10d4dbae166] [DEBUG] [ObjectStoreFileChangeListener.java:66]: Got notified from event bus: AddSharerToObjectStoreBusEvent for file test1.jpg receiving 0 sharers 
[10:57:24,662] [questCallback-072cfc60-38bd-4959-9ae3-e10d4dbae166] [DEBUG] [FileSyncer.java:80]: Got ignore event from global event bus: event.create for file test1.jpg 
[10:57:24,664] [pool-10-thread-1                                  ] [TRACE] [PathEventListener.java:43]: Got notified about the creation of '/tmp/testDir12/test1.jpg' 
[10:57:24,695] [pool-10-thread-1                                  ] [TRACE] [PathEventListener.java:64]: Got notified about the modifying of '/tmp/testDir12/test1.jpg' 
[10:57:24,724] [questCallback-072cfc60-38bd-4959-9ae3-e10d4dbae166] [INFO ] [FilePushRequestHandler.java:162]: Checksums match. Stopping exchange 072cfc60-38bd-4959-9ae3-e10d4dbae166 
[10:57:24,725] [questCallback-072cfc60-38bd-4959-9ae3-e10d4dbae166] [DEBUG] [FileSyncer.java:88]: Got clean up ignore events event from global event bus for file test1.jpg 
[10:57:24,727] [pool-10-thread-1                                  ] [TRACE] [PathEventListener.java:64]: Got notified about the modifying of '/tmp/testDir12/test1.jpg' 
[10:57:24,728] [questCallback-072cfc60-38bd-4959-9ae3-e10d4dbae166] [TRACE] [Node.java:185]: Sending object to peer with address 192.168.1.43:4003 

```

**Comment by rmatil** [comment]
Then, the FilePushExchangeHandler is not started:

```
[10:57:35,064] [pool-6-thread-1                                   ] [INFO ] [FileSyncer.java:113]: Ignoring (org.rmatil.sync.core.syncer.file.FileSyncer@faea5f) syncing of event event.create for path test1.jpg on client 192.168.1.59:4003) 
[10:57:35,066] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:133]: Syncing event event.modify for path test1.jpg on client 192.168.1.59:4003) 
[10:57:35,073] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:149]: Starting file offer exchange handler for exchangeId 5edd6e34-451e-40a8-bd28-19e52ca95a89 
[10:57:35,075] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:156]: Waiting for offer exchange 5edd6e34-451e-40a8-bd28-19e52ca95a89 to complete... (Max. 30000ms) 
[10:57:35,239] [defaultEventExecutorGroup-3-97                    ] [DEBUG] [DhtGetListener.java:29]: [Peer @ 192.168.1.59:4003]: Get of data succeeded.  
[10:57:35,251] [changeHandler-5edd6e34-451e-40a8-bd28-19e52ca95a89] [DEBUG] [ANetworkHandler.java:90]: Sending request 5edd6e34-451e-40a8-bd28-19e52ca95a89 to node 192.168.1.43:4003. Timestamp: 315534455251 
[10:57:35,252] [changeHandler-5edd6e34-451e-40a8-bd28-19e52ca95a89] [TRACE] [Node.java:185]: Sending object to peer with address 192.168.1.43:4003 
[10:57:35,292] [changeHandler-5edd6e34-451e-40a8-bd28-19e52ca95a89] [DEBUG] [ANetworkHandler.java:86]: Ignoring receiver address 192.168.1.59:4003 since it is the own node's address 
[10:57:35,305] [defaultEventExecutorGroup-2-26                    ] [DEBUG] [LocalStateObjectDataReplyHandler.java:231]: Using org.rmatil.sync.core.messaging.fileexchange.offer.FileOfferExchangeHandler as handler for response 5edd6e34-451e-40a8-bd28-19e52ca95a89 
[10:57:35,306] [defaultEventExecutorGroup-2-26                    ] [INFO ] [ANetworkHandler.java:166]: Received response for exchange 5edd6e34-451e-40a8-bd28-19e52ca95a89 of node a1eb4bd8-f4cb-4588-96ba-704b5cb03a68 (192.168.1.43:4003) 
[10:57:35,318] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:266]: Starting filePush handler for exchangeId 5edd6e34-451e-40a8-bd28-19e52ca95a89 
[10:57:35,319] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:274]: Waiting for exchange 5edd6e34-451e-40a8-bd28-19e52ca95a89 to complete... 
[10:57:35,398] [defaultEventExecutorGroup-3-11                    ] [DEBUG] [DhtGetListener.java:29]: [Peer @ 192.168.1.59:4003]: Get of data succeeded.  
[10:58:05,322] [pool-6-thread-1                                   ] [ERROR] [SyncFileChangeListener.java:70]: Error in SyncFileChangeListener Thread. Message: null 
java.lang.NullPointerException
    at org.rmatil.sync.network.core.ANetworkHandler.await(ANetworkHandler.java:133)
    at org.rmatil.sync.core.messaging.fileexchange.push.FilePushExchangeHandler.await(FilePushExchangeHandler.java:178)
    at org.rmatil.sync.core.syncer.file.FileSyncer.sync(FileSyncer.java:276)
    at org.rmatil.sync.core.syncer.file.SyncFileChangeListener.run(SyncFileChangeListener.java:63)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[10:58:05,338] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:133]: Syncing event event.modify for path test1.jpg on client 192.168.1.59:4003)
[10:58:05,339] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:149]: Starting file offer exchange handler for exchangeId d773705d-79d2-452c-8027-9cab38d730f1 
[10:58:05,340] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:156]: Waiting for offer exchange d773705d-79d2-452c-8027-9cab38d730f1 to complete... (Max. 30000ms) 
[10:58:05,483] [defaultEventExecutorGroup-3-23                    ] [DEBUG] [DhtGetListener.java:29]: [Peer @ 192.168.1.59:4003]: Get of data succeeded.  
[10:58:05,496] [changeHandler-d773705d-79d2-452c-8027-9cab38d730f1] [DEBUG] [ANetworkHandler.java:90]: Sending request d773705d-79d2-452c-8027-9cab38d730f1 to node 192.168.1.43:4003. Timestamp: 315534485496 
[10:58:05,497] [changeHandler-d773705d-79d2-452c-8027-9cab38d730f1] [TRACE] [Node.java:185]: Sending object to peer with address 192.168.1.43:4003 
[10:58:05,521] [changeHandler-d773705d-79d2-452c-8027-9cab38d730f1] [DEBUG] [ANetworkHandler.java:86]: Ignoring receiver address 192.168.1.59:4003 since it is the own node's address 
[10:58:05,529] [defaultEventExecutorGroup-2-27                    ] [DEBUG] [LocalStateObjectDataReplyHandler.java:231]: Using org.rmatil.sync.core.messaging.fileexchange.offer.FileOfferExchangeHandler as handler for response d773705d-79d2-452c-8027-9cab38d730f1 
[10:58:05,530] [defaultEventExecutorGroup-2-27                    ] [INFO ] [ANetworkHandler.java:166]: Received response for exchange d773705d-79d2-452c-8027-9cab38d730f1 of node a1eb4bd8-f4cb-4588-96ba-704b5cb03a68 (192.168.1.43:4003) 
[10:58:05,531] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:266]: Starting filePush handler for exchangeId d773705d-79d2-452c-8027-9cab38d730f1 
[10:58:05,533] [pool-6-thread-1                                   ] [DEBUG] [FileSyncer.java:274]: Waiting for exchange d773705d-79d2-452c-8027-9cab38d730f1 to complete... 
[10:58:05,606] [defaultEventExecutorGroup-3-37                    ] [DEBUG] [DhtGetListener.java:29]: [Peer @ 192.168.1.59:4003]: Get of data succeeded.  
[10:58:35,535] [pool-6-thread-1                                   ] [ERROR] [SyncFileChangeListener.java:70]: Error in SyncFileChangeListener Thread. Message: null 
java.lang.NullPointerException
    at org.rmatil.sync.network.core.ANetworkHandler.await(ANetworkHandler.java:133)
    at org.rmatil.sync.core.messaging.fileexchange.push.FilePushExchangeHandler.await(FilePushExchangeHandler.java:178)
    at org.rmatil.sync.core.syncer.file.FileSyncer.sync(FileSyncer.java:276)
    at org.rmatil.sync.core.syncer.file.SyncFileChangeListener.run(SyncFileChangeListener.java:63)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[11:00:28,946] [defaultEventExecutorGroup-2-29                    ] [DEBUG] [LocalStateObjectDataReplyHandler.java:184]: Using org.rmatil.sync.core.syncer.background.fetchobjectstore.FetchObjectStoreRequestHandler as handler for request 8db61f3b-9153-48e0-863d-f9d7696ef6e2 
[11:00:28,980] [questCallback-8db61f3b-9153-48e0-863d-f9d7696ef6e2] [TRACE] [Node.java:185]: Sending object to peer with address 192.168.1.43:4003 

```

**Comment by rmatil** [comment]
Whole log file
[odroid.txt](https://github.com/p2p-sync/sync/files/139306/odroid.txt)

**Comment by rmatil** [comment]
The same does not happen if using OS X as clients

**Comment by rmatil** [comment]
Could not reproduce this issue anymore. Closing this as for now
